### ISSUE TITLE
Missing sections in pages

### ISSUE THREAD

**Issue by fedenanni** [bgamari/mediawiki-annotate#1]
The other day we noticed that sometimes a few sections are missing from the document structure.
In the examples below you can see that the entry Anarchism (https://en.wikipedia.org/wiki/Anarchism) in the cbor file has only 3 sections, while the other pages have all the sections.

[0L, 'Anarchism'] <-- title page
Lead Section <--- sections in the cbor file
Etymology and terminology
History
External links

[0L, 'Autism']
Lead Section
Characteristics
Causes
Mechanism
Diagnosis
Screening
Prevention
Management
Society and culture
Prognosis
Epidemiology
History
References
Further reading
External links

[0L, 'Albedo']
Lead Section
Terrestrial albedo
Astronomical albedo
Examples of terrestrial albedo effects
Other types of albedo
See also
References
External links

[0L, 'An American in Paris']
Lead Section
Background
Composition
Instrumentation
Response
Preservation status
Recordings
Use in film
References
Further reading
External links

**Comment by bgamari** [comment]
Anarchism is particular is a malformed document. I've [fixed](https://en.wikipedia.org/w/index.php?title=Anarchism&diff=741696291&oldid=741604072) the document source.
