### ISSUE TITLE
Separate the mediawiki annotation from experiments

### ISSUE THREAD

**Issue by laura-dietz** [bgamari/mediawiki-annotate#2]
At the moment, the repository depends on a submodule hosted on smart-cactus that is not public (simpl-ir), inhibiting the open source status of this code project.

It is also unclear why the mediawiki annotator should depend on simpl-ir at all. Maybe it is time to split out the part of the code that runs some initial experiments into a different repository.

**Comment by bgamari** [comment]
Fixed.
